### ISSUE TITLE
no emails

### ISSUE THREAD

**Issue by luxpatrick** [s22-tech/Yourls-Email-Notify#1]
Hi, the plugin simply doesn't seem to work as I'm not receiving emails. Are there some systems requirements I can check?

**Comment by s22-tech** [comment]
It uses the code from Yourls to send the email.  Are you getting any errors in the Yourls log?  

Set $log_errors on line 22 to 'yes', change $path on line 20 to match your server, and let me know what gets saved there when you click a short link.

**Comment by luxpatrick** [comment]
its now like this, sorry I'm a novice. I don't get a log. 

$user_name  = get_current_user();
$path = '/www/htdocs/********/lux.jetzt_yourls/'.$user_name.'/projects';
$error_log = $path.'/logs/yourls.txt';
$log_errors = 'yes';

**Comment by s22-tech** [comment]
If your $path is correct, then you should get a file named “yours.txt" in that directory.  If you don’t know your path, you’ll need to contact your host for that information.

**Comment by luxpatrick** [comment]
There still is no log, but I had a look at the database. The email address I enter in the plugins field where to receive the emails alters the admin_email in the yourls_options
does that help finding the problem?

**Comment by s22-tech** [comment]
I just uploaded a new version, removing an if block for testing.  Change $path again to your server settings and let me know what gets printed.

**Comment by luxpatrick** [comment]
by no change. I'll ask someone who is savvy with php. Are there any requirements in case of permissions or functions? I'm on a shared host. 
Thanks for your help! Happy Christmas!

**Comment by s22-tech** [comment]
You may need PHP 7 or higher, but there are no other requirements.

You’re welcome, and good luck!  Let us know what you find out.

**Comment by luxpatrick** [comment]
The log functions doesn’t seem to work but we don’t know why. My friend, who is php savvy doesn’t have an idea why it’s not logging.

**Comment by luxpatrick** [comment]
We investigated the email_to field is empty. The email address you enter into the backend is written to the database as admin_email. So the email has no recipient. 
The log isn’t working as the two variables error_log and log_errors are missing.

**Comment by s22-tech** [comment]
> The log functions doesn’t seem to work but we don’t know why. My friend, who is php savvy doesn’t have an idea why it’s not logging.

    Perhaps you need a new friend? ;)

> We investigated the email_to field is empty.

    As stated in the code, that email value is pulled from the yourls db.  Check the yourls_options table.  Is it populated?

    Also, did you populate the email address on the "Click Notification Email Address" admin page under Manage Plugins?

> The log isn’t working as the two variables error_log and log_errors are missing.

    I’m not sure what you mean by “missing".   $log_errors can’t be missing as it’s declared with a value of ‘yes’.

    I use this script every day with no problems.  Plus I double-checked everything after your first post here.  

    Some ideas:
	• Does yourls work at all for you?  When you click the short url, are you taken to the long url?
	• Double-check the path on your server again.  $path in this script is specific for my server, so I’ll bet that’s part of your problem.  Don’t use '/projects’ if it’s not on your server.

    Since you stated that you’re a newbie, you really should get some experience under your belt, especially if you’re going to be working with yourls.  It’s not the easiest script to work with and the documentation is pretty scarce, especially for plug-ins.

    I’m sorry I can’t help you further.  Good luck!

**Comment by luxpatrick** [comment]
> Also, did you fill in the email address on the "Click Notification Email Address" admin page under Manage Plugins?

Yes, it alters the ADMIN_EMAIL in the db. Not an  EMAIL_TO that should be the emails recipient as I guess. 

> Does yourls work at all for you?  When you click the short url, are you taken to the long url?
sure, its working fine.

**Comment by s22-tech** [comment]
> Not an EMAIL_TO that should be the emails recipient as I guess.

That could be a big reason why you’re not getting the emails.  Fill it in and try it again.

**Comment by luxpatrick** [comment]
The field your plugin creates in the backend alters the admin email not the email_to. I think this is a mixing up. We altered your script and its now working properly as supposed.

**Comment by s22-tech** [comment]
I added both email fields to the admin page so you don’t have to get into the db.  I also updated the read me with better information.

This script was originally meant only for my use, and there’s still a lot of specialized code in it, but your questions made me look at it with fresh eyes.  Hopefully, these changes will make it easier for others to use.

**Comment by luxpatrick** [comment]
Thanks, will have a look at it.

**Comment by luxpatrick** [comment]
you've forgotten to add the function to update the email_to in the database.

**Comment by s22-tech** [comment]
> you've forgotten to add the function to update the email_to in the database.

You’re right.  Fixed and tested.  Everything should be working correctly now.

**Comment by luxpatrick** [comment]
just wanted to be sure you won't be bothered by other novices any more.
