### ISSUE TITLE
Feature request: As an Admin get an email when someone is adding a new short URL

### ISSUE THREAD

**Issue by glowfishDE** [s22-tech/Yourls-Email-Notify#3]
Hi,

since i experienced a lot of Spam to my instance, i think a feature that allows you as an admin to get email notifications that someone with the IP xyz has just added a new shortened URL to your database.

Can your plugin be used for that or can it be enhanced like this? That would be really fancy.

**Comment by s22-tech** [comment]
It sounds like you have a public install.  This was written for my private installation.  Since I have no need for a feature like that, nor any way to test it, I don’t think I will be adding a feature like this, although it sounds like a good one!  Sorry.

**Comment by glowfishDE** [comment]
hey there. Where is the difference in making your add-on sending an e-mail when someone clicks an shortened url or sending an e-mail when a new short URL is created in the database? thats just a different operation (sql query?) but your email notification plugin could be adopted to make that happen.

And you say you have no way to test that. Uh? Just create a short URL and see if you get an e-mail to your adress.

I see that you do not need that feature for your install, but it would be a great enhancement to your plugin for all of us users who have public installs. I think it might be easy to add for someone with your skills. So please give it a try

**Comment by gehwissenlos** [comment]
I forked this project and removed all things I don't need (logfile, ip table, ...). Perhabs this is usefull for you too.
You can find it here: https://github.com/gehwissenlos/Yourls-Email-Notify
