### ISSUE TITLE
Get blank page instead of being redirected

### ISSUE THREAD

**Issue by jeffshead** [s22-tech/Yourls-Email-Notify#5]
With both PHP 8.0 and PHP 8.1, I get the email but the redirect fails (blank page) when the plugin is enabled. Everything seems to work with PHP 7.4 but 7.4 is EOL tomorrow.

I see the following error in my Apache log:

```
[Sat Nov 26 21:46:12.640250 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] PHP Fatal error:  Uncaught Error: mysqli_result object is already closed in /home/site/public_html/user/plugins/email-notify/plugin.php:150
[Sat Nov 26 21:46:12.640357 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] Stack trace:
[Sat Nov 26 21:46:12.640839 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] #0 /home/site/public_html/user/plugins/email-notify/plugin.php(150): mysqli_result->fetch_object()
[Sat Nov 26 21:46:12.641245 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] #1 /home/site/public_html/includes/functions-plugins.php(224): s22_email_notification()
[Sat Nov 26 21:46:12.641652 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] #2 /home/site/public_html/includes/functions-plugins.php(275): yourls_apply_filter()
[Sat Nov 26 21:46:12.641997 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] #3 /home/site/public_html/includes/functions.php(242): yourls_do_action()
[Sat Nov 26 21:46:12.642329 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] #4 /home/site/public_html/includes/functions.php(289): yourls_redirect()
[Sat Nov 26 21:46:12.642677 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] #5 /home/site/public_html/yourls-go.php(21): yourls_redirect_shorturl()
[Sat Nov 26 21:46:12.642997 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] #6 /home/site/public_html/yourls-loader.php(52): require_once('...')
[Sat Nov 26 21:46:12.643073 2022] [:error] [pid 31607:tid 139976910026496] [client 33.123.248.25:0] #7 {main}
```

Maybe related to this: https://punbb.informer.com/forums/topic/30836/errors-with-php-80/

**Comment by s22-tech** [comment]
I just uploaded a newer file.  Try this one and let me know if it fixes your problem, since I can't duplicate it here.

**Comment by jeffshead** [comment]
I'm not sure what's going on at the moment. It seems to be hit or miss when testing. Sometimes Yourls records a click and sometimes it doesn't.

What are acceptable formats for the IP's listed in the bot and my IP files? Do they have to be single IP's, each on a separate line, CIDR, ranges, put in an array...

**Comment by s22-tech** [comment]
The bot file lists domains only, one per line, not IP's.  The my_ip file is only a single line with your IP in 1.2.3.4 format.  I have a script that populates that automatically when it changes.  That's only to prevent your visits from triggering the email.  You can remove that if you want.

**Comment by jeffshead** [comment]
I really appreciate your efforts.

I'm still testing. I think I may have found a bug or maybe I'm not understanding the use of queries with Yourls . If I have the following short link:
`https://sho.rt/test?par1=red&par2=blue`

Shouldn't the output in the email be:
```
Query items passed:
   	par1 = red
        par2 = blue

• query items have been urldecode'd
```

Below is what I actually get in the email:
```
Query items passed:
   	par1 = redpar2

• query items have been urldecode'd
```

**Comment by s22-tech** [comment]
Jeff,

I see what's happening now.  I coded this to parse parameters in the long url, not the short url.  Check out line 53 of the plugin.  It will handle a single parameter in the short url, but it wasn't designed to handle any.  It seems to me that adding multiple parameters to the short url kind of defeats the purpose of YOURLS.   :\

Marc

**Comment by s22-tech** [comment]
Well, you lit a fire under me.  I was able to add support for multiple query string parameters in the short url.  Try it out and let me know.   : )

**Comment by s22-tech** [comment]
FYI, I did some more cleanup and released version 1.8

**Comment by jeffshead** [comment]
Thanks so much for the updates but I don't know what happened... It was working with version 1.6. I deactivated the plugin and uploaded v1.7 and activated the plugin. Everything in Yourls is functioning but I stopped getting emails. I have searched all log files on my server and found no errors. I switched back to v1.6 (which was working) and still no emails. I then tried v1.8 but still no emails and no errors in any logs. I tried different email addresses and I removed the links to the bots, my IP and error log files in the plugin settings. 

I created a test script with a simple PHP mail() function and uploaded it to the Yourls root and it sends emails using the same email addresses that I have specified in the plugin so I know the mail() function is still working. I rebooted the server but that did not help either. I'm baffled and don't know what else to try.

**Comment by s22-tech** [comment]
Looking at the mail() command, maybe it was a little too strict.  Try v1.9 and let me know.

**Comment by jeffshead** [comment]
Unfortunately, not getting emails with v1.9, either.

I performed another test. I uploaded a PHP file to **/user/plugins/email-notify**. The file contains the following code:

```
<?php
$sender = 'info@example.com';
$recipient = 'user@example2.com';

$subject = "php mail test";
$message = "php test message";
$headers = 'From:' . $sender;

if (mail($recipient, $subject, $message, $headers))
{
    echo "Message accepted";
}
else
{
    echo "Error: Message not accepted";
}
?>
```
I receive an email from this file every time I access it.

**Comment by s22-tech** [comment]
OK, try this.  Comment out lines 265, 266, 267, and 269:
```
if (!file_exists(S22_CRAWLER_FILE) && $notify_me === 'yes'
  || file_exists(S22_CRAWLER_FILE) && s22_is_crawler(S22_CRAWLER_FILE) == '' && $notify_me === 'yes'
) {
  mail(S22_EMAIL_TO, $email_subject, $email_body, $headers);
 }
```
leaving just the mail command:
`mail(S22_EMAIL_TO, $email_subject, $email_body, $headers);`

Mail should be sent then, as there are no other blocks.

**Comment by s22-tech** [comment]
You may also want to try commenting out line 62:

https://github.com/s22-tech/Yourls-Email-Notify/blob/master/user/plugins/email-notify/plugin.php#L62

**Comment by jeffshead** [comment]
Sorry, still not getting emails after commenting out lines 62, 265-267 and 269.

**Comment by jeffshead** [comment]
No emails from any shorturl's. Everything else works. Every redirect is successful and every click is logged.

I even rebuilt my server and removed varnish so nothing is cached. I now have just **NGINX->Apache**.
I have created a ton of different short URL's. Below are some samples:

https://domain.com/t
https://domain.com/test
https://domain.com/test?parm1=red
https://domain.com/test?parm1=red&parm2=green
https://domain.com/test?parm1=red&parm2=green&parm3=blue

I have tried external and internal log URL's. They all work; just no emails.

**Comment by s22-tech** [comment]
This may be a dumb question, but do you have S22_EMAIL_TO populated with a good address?

**Comment by jeffshead** [comment]
Yes, I've even tried a few different email addresses.

I also replaced the entire PHP mail() function, in **plugin.php** with a PHPMailer function so that I could specify a SMTP server. That did not help, either. However, both the PHP mail() and the PHPMailer functions work if I copy them to seperate files, in the plugin folder, and access them directly.

**Comment by s22-tech** [comment]
Well then, I'm at a loss.  I'll leave you with a few suggestions, but unfortunately, there's nothing more I can do on this end.

- in /user/config.php turn on debugging:  define('YOURLS_DEBUG', true); and see what's shown in admin
- add more stretegically placed s22_print_to_log() commands in the code to see what's produced
- start removing chucks of code to see if that helps (if so, narrow it down further to find the offending line)

If you happen to find the problem, please let me know.  Good luck!

**Comment by jeffshead** [comment]
Finally, some progress. I can now reproduce the issue at will. If you edit the code in **plugin.php** and have a typo, the plugin gets deactivated. After you correct the typo or even replace **plugin.php** with a fresh, untouched copy and re-activate, it still fails to send email. The only way that I could get it working again was to drop all tables in the Yourls database and upload a fresh copy of all of the Yourls files (including all plugins) and then reconfigure everything. Then it would stop working again if I made a bad code edit. Rinse & repeat...

However, this last time that it stopped sending emails, I fixed the typo in **plugin.php** and I deactivated all plugins. I then activated the Yourls-Email-Notify plugin first and then activated the rest of the plugins. That worked!

I have know idea why deactivating all of the plugins and then reactivating them in a certain order is necessary. Do you?

These are the plugins that I'm using:
[404 if not found](https://github.com/YOURLS/404-if-not-found/)
[Allow Hyphens in Short URLs](http://yourls.org/)
[Email Notifier](https://github.com/s22-tech/Yourls-email-notify/)
[Every Click Counts](http://github/bstname/every-click-counts)
[GWall Change Logo](https://github.com/gioxx/YOURLS-GWallChangeLogo)
[GWall Change Title](https://github.com/gioxx/YOURLS-GWallChangeTitle)
[Ip-Viewer](https://github.com/faab007nl/Yourls-Ip-Viewer)
[Keep Query String](https://srvu.cc/admin/(no%20info))
[Time Zones ⏰](https://github.com/YOURLS/timezones)

**Comment by s22-tech** [comment]
No, I don't.  And that doesn't sound right, either.  I make mistakes all the time while I'm experimenting with plugins, and never once have I experienced anything like you described.  If that keeps happening, you should create an issue on the YOURLS page.

You said you could now reproduce the issue, but you don't mention what it is.  Are you able to send emails now?  Or are you getting errors now?

What text editor are you using to make the changes?  Hopefully it's not a word processor, as that will create problems.  If you're on a Mac, BBEdit is fantastic to use!

I released a new version today, and I tested it extensively before uploading it, so I know it works.  Hopefully it will work for you, as well.

**Comment by jeffshead** [comment]
> You said you could now reproduce the issue, but you don't mention what it is

Not sending emails and no errors in any server logs.
>  Are you able to send emails now?

Yes, without error.
> What text editor are you using

EditPad Pro on Windows

I just installed v1.9.2. So far, so good. Thank you!

**Comment by jeffshead** [comment]
As I mentioned in a previous post, if I make a coding mistake while editing the Yourls-Email-Notify plugin, I have to deactivate multiple plugins and reactivate the Yourls-Email-Notify plugin first, then reactivate the others. That assumption was not accurate.

I narrowed down the issue. To get the Yourls-Email-Notify plugin working again after fixing my coding mistakes, the only additional step that I have to take after reactivating the Yourls-Email-Notify plugin is to deactivate/reactivate the  [Every Click Counts](https://github.com/bstname/every-click-counts) plugin.

What makes this even more strange is that every click is still logged (just not getting any emails) before deactivating/reactivating the  [Every Click Counts](https://github.com/bstname/every-click-counts) plugin so it doesn't appear to be a caching issue. Very puzzling...

What's proper etiquette? Should I report this on the Yourls page or the  [Every Click Counts](https://github.com/bstname/every-click-counts) page?

**Comment by s22-tech** [comment]
Sorry, that I don't know.
